"""add is_admin and member_id

Revision ID: 84aaf647d0c9
Revises: f1a2b3c4d5e6
Create Date: 2026-06-16 15:21:22.163009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '84aaf647d0c9'
down_revision: Union[str, None] = 'f1a2b3c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('is_admin', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('report_templates', sa.Column('member_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'report_templates', 'members', ['member_id'], ['id'])
    op.alter_column('weekly_personal_reports', 'submitted_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
    op.alter_column('weekly_personal_reports', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('weekly_personal_reports', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
    op.alter_column('weekly_personal_reports', 'submitted_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
    op.drop_constraint(None, 'report_templates', type_='foreignkey')
    op.drop_column('report_templates', 'member_id')
    op.drop_column('members', 'is_admin')
    # ### end Alembic commands ###
